<div class="row">
   <div class="col-sm-12">
      <div class="white-box">
         <div class="row row-in">
            <div class="col-lg-4 col-sm-6 row-in-br">
               <ul class="col-in">
                  <li>
                     <span class="circle circle-md bg-danger"><i class="fas fa-user-circle"></i></span>
                  </li>
                  <li class="col-last">
                     <h3 class="counter text-right m-t-15"><?php  
                        { 
                          echo  $this->sup;
                           }?>
                     </h3>
                  </li>
                  <li class="col-middle">
                     <h4>Supplier</h4>
                     <div class="progress">
                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                           <span class="sr-only">40% Complete (success)</span>
                        </div>
                     </div>
                  </li>
               </ul>
            </div>
            <div class="col-lg-4 col-sm-6 row-in-br  b-r-none">
               <ul class="col-in">
                  <li>
                     <span class="circle circle-md bg-info"><i class="fas fa-user-circle"></i></span>
                  </li>
                  <li class="col-last">
                     <h3 class="counter text-right m-t-15"><?php  
                        { 
                          echo  $this->cus;
                           }?></h3>
                  </li>
                  <li class="col-middle">
                     <h4>Customer</h4>
                     <div class="progress">
                        <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                           <span class="sr-only">40% Complete (success)</span>
                        </div>
                     </div>
                  </li>
               </ul>
            </div>
            <div class="col-lg-4 col-sm-6 b-0">
               <ul class="col-in">
                  <li>
                     <span class="circle circle-md bg-success"><i class=" fab fa-codiepie"></i></span>
                  </li>
                  <li class="col-last">
                     <h3 class="counter text-right m-t-15"><?php  
                        { 
                          echo  $this->cat;
                           }?></h3>
                  </li>
                  <li class="col-middle">
                     <h4>Category</h4>
                     <div class="progress">
                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                           <span class="sr-only">40% Complete (success)</span>
                        </div>
                     </div>
                  </li>
               </ul>
            </div>
           
         </div>
      </div>
   </div>
</div>

<div class="row">
   <div class="col-sm-12">
      <div class="white-box">
         <div class="row row-in">
           <div class="col-lg-4 col-sm-6 row-in-br">
               <ul class="col-in">
                  <li>
                     <span class="circle circle-md bg-success"><i class="fab fa-product-hunt"></i></span>
                  </li>
                  <li class="col-last">
                     <h3 class="counter text-right m-t-15"><?php  
                        { 
                          echo  $this->pro;
                           }?></h3>
                  </li>
                  <li class="col-middle">
                     <h4>Product</h4>
                     <div class="progress">
                        <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                           <span class="sr-only">40% Complete (success)</span>
                        </div>
                     </div>
                  </li>
               </ul>
            </div>
            <div class="col-lg-4 col-sm-6 row-in-br">
               <ul class="col-in">
                  <li>
                     <span class="circle circle-md bg-danger"><i class="mdi mdi-cart-outline fa-fw"></i></span>
                  </li>
                  <li class="col-last">
                     <h3 class="counter text-right m-t-15"><?php  
                        { 
                          echo  $this->pur;
                           }?>
                     </h3>
                  </li>
                  <li class="col-middle">
                     <h4>Purchase</h4>
                     <div class="progress">
                        <div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                           <span class="sr-only">40% Complete (success)</span>
                        </div>
                     </div>
                  </li>
               </ul>
            </div>
             <div class="col-lg-4 col-sm-6 b-0">
               <ul class="col-in">
                  <li>
                     <span class="circle circle-md bg-warning"><i class="mdi mdi-cart-outline fa-fw"></i></span>
                  </li>
                  <li class="col-last">
                     <h3 class="counter text-right m-t-15"><?php  
                        { 
                          echo  $this->sal;
                           }?>
                     </h3>
                  </li>
                  <li class="col-middle">
                     <h4>Sale</h4>
                     <div class="progress">
                        <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                           <span class="sr-only">40% Complete (success)</span>
                        </div>
                     </div>
                  </li>
               </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

      
    