
<div id="page-wrapper">
   <div class="container-fluid">
      <div class="row bg-title">
         <div class="row">
            <div class="col-lg-12">
               <div class="white-box">
                  <h3 class="box-title">Customer Form</h3>
                  <?php echo $this->customerform;?>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>