
<!--  -->
<div id="page-wrapper">
   <div class="container-fluid">
      <div class="row bg-title">
         <div class="row">
            <div class="col-lg-12">
               <div class="white-box">
                  <h3 class="box-title">Customer Table</h3>
                  <p class="text-muted">This is the table of Customer Detail</p>
                  <table class="table table-striped table-bordered" id="editable-datatable">
                     <thead>
                        <tr>
                           <th>Customer Id</th>
                            <th>image</th>
                            <th>Customer Name</th>
                            <th>Customer Address</th>
                            <th>Customer Email</th>
                            <th>Customer Contact</th>
                            <th>Status</th>
                            <th>Page Count</th>
                            <th>Date_created</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody>
                        <?php if($this->customers){
                            foreach($this->customers as $cus){
                              ?>
                        <tr id="1" class="gradeX">
                          <td><?=$cus->getCustomerId(); ?> </td>
                <td ><img width="100px" height="100px" src="/images/<?= $cus->getImage(); ?>"></td>      
                <td><?=$cus->getName();?></td>
                <td><?=$cus->getAddress();?></td>
                <td><?=$cus->getEmail();?></td>
                <td><?=$cus->getContact();?></td>
                <td><?php  if($cus->getStatus()){ echo 'Publish'; }else{ echo 'UnPublish';} ?></td>
                <td><?= $cus->getSaleCount(); ?></td>
                <td> <?= $cus->getCreatedDate();?> </td>
                   <td>

                    <?php if(!$cus->getStatus()){?>
                             <a href="/Customer/activate?id=<?= $cus->getCustomerId(); ?>" class="btn btn-info btn-rounded"><i class="fa fa-thumbs-up"></i>Publish</a>
                           <?php } ?>
                           <?php if($cus->getStatus()){?>
                       
                            <a href="/Customer/deactivate?id=<?= $cus->getCustomerId(); ?>"  class="btn btn-warning btn-rounded"><i class="fa fa-thumbs-up"></i>Unpublish</a>
                            <?php } ?>
                            <a class="btn btn-danger btn-rounded" href="/Customer/delete?id=<?=$cus->getCustomerId(); ?>"> <i class="fa fa-trash"></i> Delete</a>
                            <a class="btn btn-primary btn-rounded" href="/Customer/update?id=<?=$cus->getCustomerId(); ?>"><i class="fa fa-edit"></i> Update</a>
                  </td>
          </tr>
          <?php

            }
          }
 ?>

                     </tbody>
                     <tfoot>
                        <tr>
                           <th>Customer Id</th>
                            <th>image</th>
                            <th>Customer Name</th>
                            <th>Customer Address</th>
                            <th>Customer Email</th>
                            <th>Customer Contact</th>
                            <th>Status</th>
                            <th>Page Count</th>
                            <th>Date_created</th>
                           <th>Action</th>
                        </tr>
                     </tfoot>
                  </table>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<?php $this->headScript()->prependFile('/plugins/bower_components/styleswitcher/jQuery.style.switcher.js'); ?>
<?php $this->headScript()->captureStart(); ?>
$('#mainTable').editableTableWidget().numericInputExample().find('td:first').focus();
$('#editable-datatable').editableTableWidget().numericInputExample().find('td:first').focus();
$(document).ready(function() {
$('#editable-datatable').DataTable();
});
<?php $this->headScript()->captureEnd(); ?>
<?php $this->headScript()->prependFile('/plugins/bower_components/tiny-editable/numeric-input-example.js'); ?>
<?php $this->headScript()->prependFile('/plugins/bower_components/tiny-editable/mindmup-editabletable.js'); ?>
<?php $this->headScript()->prependFile('/plugins/bower_components/datatables/datatables.min.js'); ?>
<?php $this->headScript()->prependFile('/plugins/bower_components/jquery-datatables-editable/jquery.dataTables.js'); ?>