<html lang="en">

<!-- Mirrored from www.ampleadmin.wrappixel.com/ampleadmin-html/ampleadmin/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 29 Aug 2018 20:28:15 GMT -->
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" type="image/png" sizes="16x16" href="../plugins/images/favicon.png">
<title>Store Login</title>


<link href="/ampleadmin/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
<!-- animation CSS -->
<link href="/ampleadmin/css/animate.css" rel="stylesheet">
<!-- Custom CSS -->
<link href="/ampleadmin/css/style.css" rel="stylesheet">
<!-- color CSS -->
<link href="/ampleadmin/css/colors/default.css" id="theme"  rel="stylesheet">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

</head>
<body>
<!-- Preloader -->
<div class="preloader">
  <div class="cssload-speeding-wheel"></div>
</div>
<section id="wrapper" class="new-login-register">
      <div class="lg-info-panel">
              <div class="inner-panel">
                  <a href="javascript:void(0)" class="p-20 di"><img src="../plugins/images/admin-logo.png"></a>
                  <div class="lg-content">
                      <h2>STORE KEEPER</h2>
                      <p class="text-muted">->PowerBy Nishan Gautam</p>
                      <a href="/index/" class="btn btn-rounded btn-danger p-l-22 p-r-20">Login</a>
                  </div>
              </div>
      </div>
      <div class="new-login-box">
                <div class="white-box">
                    <h3 class="box-title m-b-0">Sign In to Admin</h3>
                    <small>Enter your details below</small>
                 
                    
                    <?php echo $this->loginform;?>
                    <div class="row">
                      <div class="col-xs-12 col-sm-12 col-md-12 m-t-10 text-center">
                        <div class="social"><a href="javascript:void(0)" class="btn  btn-facebook" data-toggle="tooltip"  title="Login with Facebook"> <i aria-hidden="true" class="fab fa-facebook-f"></i> </a> <a href="javascript:void(0)" class="btn btn-googleplus" data-toggle="tooltip"  title="Login with Google"> <i aria-hidden="true" class="fab fa-google-plus-g"></i> </a> </div>
                      </div>
                    </div>
                   
                  
                </div>
      </div>            
  
  
</section>
<!-- jQuery -->
<script src="/plugins/bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap Core JavaScript -->
<script src="/ampleadmin/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- Menu Plugin JavaScript -->
<script src="/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js"></script>

<!--slimscroll JavaScript -->
<script src="/ampleadmin/js/jquery.slimscroll.js"></script>
<!--Wave Effects -->
<script src="/ampleadmin/js/waves.js"></script>
<!-- Custom Theme JavaScript -->
<script src="/ampleadmin/js/custom.min.js"></script>
<!--Style Switcher -->
<script src="/plugins/bower_components/styleswitcher/jQuery.style.switcher.js"></script>
</body>

<!-- Mirrored from www.ampleadmin.wrappixel.com/ampleadmin-html/ampleadmin/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Wed, 29 Aug 2018 20:28:15 GMT -->
</html>
