<div id="page-wrapper">
   <div class="container-fluid">
      <div class="row bg-title">
         <div class="row">
            <div class="col-lg-12">
               <div class="white-box">
                  <h3 class="box-title">Purchase Table</h3>
                  <p class="text-muted">This is the table of Purchase Detail</p>
                  <form method="post">
                       <div class="col-sm-2">
                        <label>Supplier:</label>
                        <select class="form-control col-sm-2" name="supplier_id" id="supplier_id" required="">
                            <option value="0">...Supplier Name...</option>
                           <?php foreach($this->suppliers as $item){?>
                           <option value="<?=$item->getSupplierId(); ?>" /Required>
                              <?= $item->getName(); ?>
                           </option>
                           <?php   } ?>
                        </select>
                        <div>&nbsp;</div>
                     </div> 
                    
                     
                     
                     <table class="table table-bordered" id="table">
                        <thead>
                           <tr>
                              <th>Category Name</th>
                              <th>Product Name</th>
                              <th>Quantity</th>
                              <th>Rate</th>
                              <th>Discount</th>
                              <th>Action</th>
                           </tr>
                        </thead>
                        <tbody>
                           <tr rowId="0">
                              <td>
                                 <select  class="form-control col-sm-2 category_id " name="category_id" rowId="0" id="category_id0" required>
                                    <option value="0">...Category Name.</option>
                                    <?php foreach($this->categories as $cat){ ?>
                                    <option value="<?= $cat->getCategoryId();?>">
                                       <?= $cat->getCategory(); ?>
                                    </option>
                                    <?php  } ?>
                                 </select>
                              </td>
                              <td>
                                 <select class="form-control col-sm-2 product_id" name="product_id[]" class="product_id" rowId="0" id="product_id0" required>
                                    <option value="0" >..Product Name..</option>
                                 </select>
                              </td>
                              <td>
                                 <input class="form-control col-sm-2 product_quantity" type="text" name="product_quantity[]" id="product_quantity0" rowId="0" placeholder="Per Product..." required="Please Insert Product Quantity">
                              </td>
                              <td>
                                 <input class="form-control col-sm-1 price" type="text" name="price[]" id="price0"  rowId="0" value="" placeholder="Rs...." required="" >
                              </td>
                              <td>
                                 <input class="form-control col-sm-1 discount" type="text" name="discount[]" id="discount0"  rowId="0" placeholder="%" required="">
                              </td>
                              <!--  -->
                              <td>
                                  <button type="button" class="btn btn-success " onclick="addRow()"><i class="fa fa-check"></i></button>
                                  <button type="button" class="btn btn-danger remove" rowId="0"><i class="fa fa-times"></i></button>
                                 
                                 
                              </td>
                           </tr>
                           
                        </tbody>
                     </table>
                     <!-- <button type="button" onclick="addRow()">Add item</button> -->
                     <br />
                     <br />

                     <button type="submit" name="submit" onclick="submit()" class="btn btn-lg btn-info btn-rounded">Add Purchase</button>
                  </form>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

<?php $this->headScript()->captureStart(); ?>
$(document).ready(function() {

    $('.category_id').change(function() {
        var rowId = $(this).attr('rowId');
        var cat_id = $(this).val();
        $.get('/api/product/list', {
            category_id: cat_id
        }).done(function(data) {
            var data = jQuery.parseJSON(data);
            $('#product_id' + rowId + ' option').remove();
            for (var item in data) {
                var product = data[item];
                var el = document.createElement('option');
                el.value = product.product_id;
                el.text = product.name;
                $(el).prop('data-price', product);
                $("#product_id" + rowId).append(el);
            }
             $("#product_id" + rowId).append(el).change();
        });
    });

    $('.product_id').change(function() {
        $that = $(this);
        var rowId = $(this).attr('rowId');
        var pro_id = $(this).val();
        $.get('/api/product/add', {
            product_id: pro_id
        }).done(function(data) {
            var data = jQuery.parseJSON(data);

            $('[rowid="' + $that.attr('rowid') + '"]').find('.price').val(data.price);

        });
    });
});


function addRow() {

    var lastRow = $('#table tr:last');
    var lastRowNo = parseInt($(lastRow).attr('rowId'));
    var nextRowNo = lastRowNo + 1;
    var nextRow = $(lastRow).clone(true);
    $(nextRow).attr('rowId',nextRowNo);   
    $(nextRow).find('.category_id').attr('id', 'category_id' + nextRowNo).attr('rowId', nextRowNo);
    $(nextRow).find('.product_id').attr('id', 'product_id'+ nextRowNo).attr('rowId',nextRowNo);    $(nextRow).find('.product_quantity').attr('id', 'product_quantity' + nextRowNo).attr('rowId',nextRowNo);
    $(nextRow).find('.price').attr('id','price'+ nextRowNo).attr('rowId',nextRowNo);
    $(nextRow).find('.discount').attr('id','discount' + nextRowNo).attr('rowId',nextRowNo);
   
    $('#table').append(nextRow);

}
$('.remove').on('click', removeRow);
function removeRow() {
  $that     = $(this);
  var rowId = $(this).attr('rowId');
  $('tr[rowid="' + $that.attr('rowid') + '"]').remove();
   $(this).closest('tr').next().remove();
        $(this).closest('tr').remove();
}

<?php $this->headScript()->captureEnd(); ?>