
<!--  -->
<div id="page-wrapper">
   <div class="container-fluid">
      <div class="row bg-title">
         <div class="row">
            <div class="col-lg-12">
               <div class="white-box">

                  <h3 class="box-title">Purchase Table</h3>
                  <p class="text-muted">This is the table of Purchase Detail</p>
                  <table class="table table-striped table-bordered" id="editable-datatable">
                     <thead>
                        <tr>
                            <th>S.N</th>
                            <th>Supplier Name</th>
                            <th>Date</th>
                            <th>Total(.Rs)</th>
                            <th>Action</th> 
                      </tr>
                     </thead>
                     <tbody>
                        <?php if($this->purchases){
                              foreach ($this->purchases as $pur) {
                                ?>
                        <tr id="1" class="gradeX">
                          <td><?=$pur->getPurchaseId(); ?></td>
                <td><?=$pur->getSupplier()->getName(); ?></td>
                <td><?=$pur->getCreatedDate(); ?></td>
                <td><?=$pur->getAmount(); ?> </td>
                
                <td> <a class="btn btn-info btn-rounded" href="/Purchase/view?id=<?=$pur->getPurchaseId(); ?>"> <i class="fa fa-eye"></i> View</a>
                  <a class="btn btn-danger btn-rounded" href="/Purchase/delete?id=<?=$pur->getPurchaseId(); ?>"> <i class="fa fa-trash"></i> Delete</a></td>
               
          </tr>
            <?php
            }
            }
            ?>
                     </tbody>
                     <tfoot>
                        <tr>
                           <th>S.N</th>
                            <th>Supplier Name</th>
                            <th>Date</th>
                            <th>Total(.Rs)</th>
                            <th>Action</th> 
                        </tr>
                     </tfoot>
                  </table>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
 <?php $this->headScript()->prependFile('/plugins/bower_components/styleswitcher/jQuery.style.switcher.js'); ?>
  



    <!-- end - This is for export functionality only -->
    
<?php $this->headScript()->captureStart(); ?>
$('#mainTable').editableTableWidget().numericInputExample().find('td:first').focus();
$('#editable-datatable').editableTableWidget().numericInputExample().find('td:first').focus();
$(document).ready(function() {
$('#editable-datatable').DataTable();
});
<?php $this->headScript()->captureEnd(); ?>
<?php $this->headScript()->prependFile('/plugins/bower_components/tiny-editable/numeric-input-example.js'); ?>
<?php $this->headScript()->prependFile('/plugins/bower_components/tiny-editable/mindmup-editabletable.js'); ?>
<?php $this->headScript()->prependFile('/plugins/bower_components/datatables/datatables.min.js'); ?>
<?php $this->headScript()->prependFile('/plugins/bower_components/jquery-datatables-editable/jquery.dataTables.js'); ?>
