<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<div class="container">
    <div class="row">
        <div class="well col-xs-10 col-sm-10 col-md-6 col-xs-offset-1 col-sm-offset-1 col-md-offset-3">
            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <address>
                        <strong>Keeper</strong>
                        <br>
                       Kankai-3,JhapaRoad
                        <br>
                       Surunga
                        <br>
                        <abbr title="Phone">P:</abbr> 023-550471
                    </address>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6 text-right">
                    <p>
                        <em>Date: <?php echo $this->purchase->getSupplier()->getCreatedDate(); ?></em>
                    </p>
                    <p>
                        <em>S.N #: <?php echo $this->purchase->getPurchaseId(); ?> </em>
                    </p>
                </div>
            </div>
            <div class="row">
              
                <div class="col-xs-8 col-sm-6 col-md-6">
                    <address>
                       <h4> <strong>Supplier Name:-</strong><?php echo $this->purchase->getSupplier()->getName(); ?> </h4>
                        
                        
                    </address>
                </div>
            </div>
            <div class="row">
                <div class="text-center">
                    <h1><u>Purchase Invoice</u></h1>
                </div>
                </span>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th class="text-left">Product</th>
                            <th class="text-center">Quantity</th>
                            <th class="text-center">Price</th>
                            <th class="text-center">Discount</th>
                            <th class="text-center">Total</th>
                        </tr>
                    </thead>
                    <tbody>
                       <?php if($this->purchase->getPurchaseData()){
                foreach($this->purchase->getPurchaseData() as $item){ ?>

                        
                       <td class="col-md-5 text-left"> <?=$item->getProduct()->getName(); ?></em></td>
                <td class="col-md-2 text-center"><em><?=$item->getProductQuantity();?></td>
                <td class="col-md-2 text-center"><?=$item->getPrice(); ?></td>
                <td class="col-md-1 text-center"><?=$item->getDiscount(); ?></td>
                <td class="col-md-2 text-center"><?=$item->getAmount(); ?></td>
              </tr>
              <?php
              }

            }
            ?>
                       
                       
                        <tr>
                          <td></td>
                          <td></td>
                          <td></td>
                           
                            <td class="text-right"><h4><strong>Total:</strong></h4></td>
                            <td class="text-center text-danger"><h4><strong><?php echo $this->purchase->getAmount(); ?></strong></h4></td>
                        </tr>
                    </tbody>
                </table>
                </td>
            </div>
        </div>
    </div>