
<!--  -->
<div id="page-wrapper">
   <div class="container-fluid">
      <div class="row bg-title">
         <div class="row">
            <div class="col-lg-12">
               <div class="white-box">
                  <h3 class="box-title">Login Table</h3>
                  <p class="text-muted">This is the table of Login User Detail</p>
                  <table class="table table-striped table-bordered" id="editable-datatable">
                     <thead>
                        <tr>
                           <th> Login Id</th>
                          <th>Username</th>
                         <th>Email<th>
                          <th>Status</th>
                          <th>Date</th>
                          <th>Action</th>
          
                        </tr>
                     </thead>
                     <tbody>
                             <?php
                      if($this->logins){
                        foreach($this->logins as $log){
?>
    
                        <tr id="1" class="gradeX">
                          <td><?=$log->getLoginId(); ?></td>
                <td><?=$log->getUserName();?></td>
               
                <td><?=$log->getEmail(); ?></td>
                <td></td>
                <td><?php if($log->getStatus()){ echo "Enable"; } else {echo "disable";} ?></td>
                <td><?=$log->getCreatedDate(); ?></td>
                
                   <td>
                    <?php if(!$log->getStatus()){ ?>
                              <a href="/login/activate?id=<?= $log->getLoginId();?>" class="btn btn-success btn-rounded"><i class="fa fa-thumbs-up"></i> Enable</a>
                          <?php } ?>
                           <?php if($log->getStatus()){ ?>
                         <a href="/login/deactivate?id=<?= $log->getLoginId();?>" class="btn btn-warning btn-rounded"><i class="fa fa-thumbs-down"></i> Disable</a>
                          <?php } ?>
                            <a class="btn btn-danger btn-rounded" href="/Login/delete?id=<?=$log->getLoginId(); ?>"> <i class="fa fa-trash"></i> Delete</a>
                            <a class="btn btn-primary btn-rounded" href="/Login/update?id=<?=$log->getLoginId(); ?>"><i class="fa fa-edit"></i> Update</a>
                   </td>
             </tr>
                   <?php
                 }
               }
               ?>

                     </tbody>
                     <tfoot>
                        <tr>
                             <th> Login Id</th>
                          <th>Username</th>
                         <th>Email<th>
                          <th>Status</th>
                          <th>Date</th>
                          <th>Action</th>
                        </tr>
                     </tfoot>
                  </table>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<?php $this->headScript()->prependFile('/plugins/bower_components/styleswitcher/jQuery.style.switcher.js'); ?>
<?php $this->headScript()->captureStart(); ?>
$('#mainTable').editableTableWidget().numericInputExample().find('td:first').focus();
$('#editable-datatable').editableTableWidget().numericInputExample().find('td:first').focus();
$(document).ready(function() {
$('#editable-datatable').DataTable();
});
<?php $this->headScript()->captureEnd(); ?>
<?php $this->headScript()->prependFile('/plugins/bower_components/tiny-editable/numeric-input-example.js'); ?>
<?php $this->headScript()->prependFile('/plugins/bower_components/tiny-editable/mindmup-editabletable.js'); ?>
<?php $this->headScript()->prependFile('/plugins/bower_components/datatables/datatables.min.js'); ?>
<?php $this->headScript()->prependFile('/plugins/bower_components/jquery-datatables-editable/jquery.dataTables.js'); ?>