<div class="navbar-default sidebar" role="navigation">
            <div class="sidebar-nav slimscrollsidebar">
                <div class="sidebar-head">
                    <h3><span class="fa-fw open-close"><i class="ti-menu hidden-xs"></i><i class="ti-close visible-xs"></i></span> <span class="hide-menu">KEEPER</span></h3> </div>
                <ul class="nav" id="side-menu">
                    <li class="user-pro">
                        <a href="javascript:void(0)" class="waves-effect"><img src="../plugins/images/users/nishan.JPG" alt="user-img" class="img-circle"> <span class="hide-menu"> Nishan Gautam<span class="fa arrow"></span></span>
                        </a>
                        <ul class="nav nav-second-level collapse" aria-expanded="false" style="height: 0px;">
                            <li><a href="javascript:void(0)"><i class="ti-user"></i> <span class="hide-menu">My Profile</span></a></li>
                           
                            <li><a href="/Admin/Logout"><i class="fa fa-power-off"></i> <span class="hide-menu">Logout</span></a></li>
                        </ul>
                    </li>
                    <li> <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-av-timer fa-fw" data-icon="v"></i> <span class="hide-menu"> Dashboard <span class="fa arrow"></span> <span class="label label-rouded label-inverse pull-right">1</span></span></a>
                        <ul class="nav nav-second-level">
                            <li> <a href="/index"><i class=" fa-fw">D</i><span class="hide-menu">Dashboard</span></a> </li>
                           
                        </ul>
                    </li>
                    <li> <a href="javascript:void(0);" class="waves-effect"><i class="fas fa-user-circle" data-icon="v"></i> <span class="hide-menu">Supplier <span class="fa arrow"></span> </span></a>
                        <ul class="nav nav-second-level">
                            <li> <a href="/Supplier/add"><i class="fa-fw">A</i><span class="hide-menu">Add Supplier</span></a> </li>
                            <li> <a href="/Supplier/"><i class="fa-fw">Vi</i><span class="hide-menu">View Supplier</span></a> </li>
                            
                        </ul>
                    </li>
                    <li> <a href="javascript:void(0);" class="waves-effect"><i class="fas fa-user-circle" data-icon="v"></i> <span class="hide-menu">Customer <span class="fa arrow"></span> </span></a>
                        <ul class="nav nav-second-level">
                            <li> <a href="/Customer/add"><i class="fa-fw">A</i><span class="hide-menu">Add Customer</span></a> </li>
                            <li> <a href="/Customer/"><i class="fa-fw">Vi</i><span class="hide-menu">View Customer</span></a> </li>
                            
                        </ul>
                    </li>
                    <li> <a href="javascript:void(0);" class="waves-effect"><i class="fab fa-codiepie" data-icon="v"></i> <span class="hide-menu">Category <span class="fa arrow"></span> </span></a>
                        <ul class="nav nav-second-level">
                            <li> <a href="/Category/add"><i class="fa-fw">A</i><span class="hide-menu">Add Category</span></a> </li>
                            <li> <a href="/Category/"><i class="fa-fw">Vi</i><span class="hide-menu">View Category</span></a> </li>
                            
                        </ul>
                    </li>
                    <li> <a href="javascript:void(0);" class="waves-effect"><i class="fab fa-product-hunt" data-icon="v"></i> <span class="hide-menu">Product <span class="fa arrow"></span> </span></a>
                        <ul class="nav nav-second-level">
                            <li> <a href="/Product/add"><i class="fa-fw">A</i><span class="hide-menu">Add Product</span></a> </li>
                            <li> <a href="/Product/"><i class="fa-fw">Vi</i><span class="hide-menu">View Product</span></a> </li>
                            
                        </ul>
                    </li>
                    <li> <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-cart-outline fa-fw" data-icon="v"></i> <span class="hide-menu">Purchase <span class="fa arrow"></span> </span></a>
                        <ul class="nav nav-second-level">
                            <li> <a href="/Purchase/add"><i class="fa-fw">A</i><span class="hide-menu">Add Purchase</span></a> </li>
                            <li> <a href="/Purchase/"><i class="fa-fw">Vi</i><span class="hide-menu">View Purchase</span></a> </li>
                            
                        </ul>
                    </li>
                    <li> <a href="javascript:void(0);" class="waves-effect"><i class="mdi mdi-cart-outline fa-fw" data-icon="v"></i> <span class="hide-menu">Sale <span class="fa arrow"></span> </span></a>
                        <ul class="nav nav-second-level">
                            <li> <a href="/Sale/add"><i class="fa-fw">A</i><span class="hide-menu">Add Sale</span></a> </li>
                            <li> <a href="/Sale/"><i class="fa-fw">Vi</i><span class="hide-menu">View Sale</span></a> </li>
                            
                        </ul>
                    </li>
                    <li> <a href="javascript:void(0);" class="waves-effect"><i class="ti-lock fa-fw" data-icon="v"></i> <span class="hide-menu">Login <span class="fa arrow"></span> </span></a>
                        <ul class="nav nav-second-level">
                            <li> <a href="/Login/add"><i class="fa-fw">A</i><span class="hide-menu">Add Login</span></a> </li>
                            <li> <a href="/Login/view"><i class="fa-fw">Vi</i><span class="hide-menu">View Login</span></a> </li>
                            
                        </ul>
                    </li>

                   
                </ul>
            </div>
        </div>
         <div id="page-wrapper">
            <div class="container-fluid">
                <div class="row bg-title">
                    <div class="col-lg-3 col-md-4 col-sm-4 col-xs-12">
                        <h4 class="page-title">Store Keeper</h4> </div>
                    <!-- <div class="col-lg-9 col-sm-8 col-md-8 col-xs-12">
                        <button class="right-side-toggle waves-effect waves-light btn-info btn-circle pull-right m-l-20"><i class="ti-settings text-white"></i></button>
                        <a href="javascript: void(0);" target="_blank" class="btn btn-danger pull-right m-l-20 hidden-xs hidden-sm waves-effect waves-light">Buy Admin Now</a>
                        <ol class="breadcrumb">
                            <li><a href="#">Dashboard</a></li>
                            <li class="active">Starter Page</li>
                        </ol>
                    </div> -->
                    <!-- /.col-lg-12 -->
               </div>
               
               <!--  <div class="row">
                    <div class="col-md-12">
                        <div class="white-box">
                            <h3 class="box-title">Blank Starter page</h3> </div>
                    </div>
                </div> -->
                <!-- ============================================================== -->
                <!-- Right sidebar -->
                <!-- ============================================================== -->
                <!-- .right-sidebar -->
                
                <!-- ============================================================== -->
                <!-- End Right sidebar -->
                <!-- ============================================================== -->
          
