<!--  -->
<div id="page-wrapper">
   <div class="container-fluid">
      <div class="row bg-title">
         <div class="row">
            <div class="col-lg-12">
               <div class="white-box">
                  <h3 class="box-title">Category Table</h3>
                  <p class="text-muted">This is the table of Category Detail</p>
                  <table class="table table-striped table-bordered" id="editable-datatable">
                     <thead>
                        <tr>
                           <th>Category Id</th>
                           <th>Category Name</th>
                           <th>Status</th>
                           <th>Date_Created</th>
                           <th>Page Count</th>
                           <th>Action</th>
                        </tr>
                     </thead>
                     <tbody>
                        <?php if($this->categories){
                           foreach($this->categories as $cat){ ?>
                        <tr id="1" class="gradeX">
                           <td><?= $cat->getCategoryId(); ?></td>
                           <td><?= $cat->getCategory(); ?></td>
                           <td><?php  if($cat->getStatus()){ echo 'Publish'; }else{ echo 'UnPublish';} ?></td>
                           <td><?= $cat->getCreatedDate();?></td>
                           <td><?= $cat->getProductCount(); ?></td>
                           <td>
                              <?php if(!$cat->getStatus()){?>
                              <a href="/category/activate?id=<?= $cat->getCategoryId(); ?>" class="btn btn-success btn-rounded"><i class="fa fa-thumbs-up"></i>Publish</a>
                              <?php }?>
                              <?php if($cat->getStatus()){?>
                              <a href="/category/deactivate?id=<?= $cat->getCategoryId(); ?>" class="btn btn-warning btn-rounded"><i class="fa fa-thumbs-up"></i>Unpublish</a>
                              <?php }?>
                              <a class="btn btn-danger btn-rounded" href="/Category/delete?id=<?=$cat->getCategoryId(); ?>"> <i class="fa fa-trash"></i> Delete</a>
                              <a class="btn btn-primary  btn-rounded" href="/Category/update?id=<?=$cat->getCategoryId(); ?>"><i class="fa fa-edit"></i> Update</a>
                           </td>
                        </tr>
                        <?php  }
                           } ?>
                     </tbody>
                     <tfoot>
                        <tr>
                           <th>Category Id</th>
                           <th>Category Name</th>
                           <th>Status</th>
                           <th>Date_Created</th>
                           <th>Page Count</th>
                           <th>Action</th>
                        </tr>
                     </tfoot>
                  </table>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<?php $this->headScript()->prependFile('/plugins/bower_components/styleswitcher/jQuery.style.switcher.js'); ?>
<?php $this->headScript()->captureStart(); ?>
$('#mainTable').editableTableWidget().numericInputExample().find('td:first').focus();
$('#editable-datatable').editableTableWidget().numericInputExample().find('td:first').focus();
$(document).ready(function() {
$('#editable-datatable').DataTable();
});
<?php $this->headScript()->captureEnd(); ?>
<?php $this->headScript()->prependFile('/plugins/bower_components/tiny-editable/numeric-input-example.js'); ?>
<?php $this->headScript()->prependFile('/plugins/bower_components/tiny-editable/mindmup-editabletable.js'); ?>
<?php $this->headScript()->prependFile('/plugins/bower_components/datatables/datatables.min.js'); ?>
<?php $this->headScript()->prependFile('/plugins/bower_components/jquery-datatables-editable/jquery.dataTables.js'); ?>